Finished Basic Room 3
Renamed all basic 3d objects for better readability and deactivated debug.drawline function calls for better play experience. Need to change idle from raycast to invis. collision cone.

Error: Zombies on platform do not detect player due to height difference. Can be solved with either replacing raycast with cone to facilitate vertical collision detections and/or event system and triggers